name: Deploy Super Project

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install-deps
        run: >
          sudo apt-get install -y
          ruby
          ruby-bundler
      - name: bundle install
        run: bundle install
      - name: clone process-code-software-procurement
        run: git clone https://github.com/publiccodenet/process-code-software-procurement.git software-procurement
      - name: checkout gh-pages
        run: |
          cd software-procurement
          git checkout gh-pages
          rm -rf .git
      - name: jekyll build
        run: bundle exec jekyll build
      - name: build list files
        run: find ./_site -type f
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
